/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application")
}


tasks.named<Test>("test") {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

application {
    mainClass = "org.example.Main"
}

dependencies {
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
}


group = "org.example"
version = "1.0-SNAPSHOT"
description = "jenkins-practice"
